### ISSUE TITLE
Issue #9: Create Layout for Website

### ISSUE THREAD

**Issue by ElizabethK9** [ElizabethK9/MTGDeckBuilder#9]
Create a good layout for the first page of the Website

**Comment by cameronwhite4121** [comment]
Front page should describe the site, and have links to Deck Builder, card search, life counter, and forum where other decks are published by other users. Comment feature can be added too as long as content filtering is enabled.

**Comment by cameronwhite4121** [comment]
Also should be a link for a users entire collection, separate from the deck link

**Comment by ElizabethK9** [comment]
Created extremely basic layout
